Vagrant.configure("2") do |config|
         # Box base: Ubuntu 22.04 (Jammy)
         config.vm.box = "ubuntu/jammy64"
       
         # Red privada con IP fija
         config.vm.network "private_network", ip: "192.168.33.10"
       
         # Provisionamiento con script externo (Nginx)
         config.vm.provision "shell", path: "scripts/instalar_nginx.sh"
       
         # Provisionamiento inline para Docker + kubectl
         config.vm.provision "shell", inline: <<-SHELL
           # Instalar Docker
           apt update
           apt install -y docker.io
           systemctl enable --now docker
       
           # Instalar kubectl
           curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
           install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
       
           # Verificar versiones
           docker --version && kubectl version --client
         SHELL
       end
       