# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
         # Box base
         config.vm.box = "ubuntu/bionic64"
       
         # Webserver 1
         config.vm.define "webserver1" do |web1|
           web1.vm.hostname = "webserver1"
           web1.vm.network "private_network", ip: "192.168.33.10"
         end
       
         # Webserver 2
         config.vm.define "webserver2" do |web2|
           web2.vm.hostname = "webserver2"
           web2.vm.network "private_network", ip: "192.168.33.11"
         end
         # DBwebserver
         config.vm.define "db01" do |db|
          db.vm.hostname = "db01"
          db.vm.network "private_network", ip: "192.168.33.12"
         end

       
         # Opcional: recursos (ajusta si querés)
         config.vm.provider "virtualbox" do |vb|
           vb.memory = 512
           vb.cpus = 1
         end
       end
       